apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: acme-fitness-frontend
spec:
  displayName: Acme Fitness Frontend
  description: Gorkems Acme Fitness Frontend
    
    
  iconUrl: https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Spring_Framework_Logo_2018.svg/800px-Spring_Framework_Logo_2018.svg.png
  tags:
    - spring
    - cloud
    - function
    - cloud-native-developers
  git:
    ignore: ".git/, target, catalog"
    url: https://github.com/gorkemozlu/acme-fitness-tap/frontend
    ref:
      branch: main