apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shopping-cert
  namespace: istio-system
spec:
  commonName: 'acme.apps.tkg-lab.k10s.io'
  dnsNames:
  - 'acme.apps.tkg-lab.k10s.io'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  secretName: shopping-cert