export const ADD_CART_ITEMS = "ADD_CART_ITEMS";
export const CART_ITEMS_FAILED = "CART_ITEMS_FAILED";
export const CART_ITEMS_LOADING = "CART_ITEMS_LOADING";
export const POST_CART_DATA = "POST_CART_DATA";

export const ADD_CATALOG_ITEMS = "ADD_CATALOG_ITEMS";
export const CATALOG_ITEMS_FAILED = "CATALOG_ITEMS_FAILED";
export const CATALOG_ITEMS_LOADING = "CATALOG_ITEMS_LOADING";

export const AUTH_CLIENT_LOADING = "AUTH_CLIENT_LOADING";
export const AUTH_CLIENT_FAILED = "AUTH_CLIENT_FAILED";
export const STORE_AUTH_CLIENT = "STORE_AUTH_CLIENT";
export const STORE_USER = "STORE_USER";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const TOKEN_LOADING = "TOKEN_LOADING";
export const TOKEN_ERROR = "TOKEN_ERROR";
export const SET_TOKEN = "SET_TOKEN";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_DELIVERY = "SET_DELIVERY";
export const SET_PAYMENT = "SET_PAYMENT";
export const ORDER_LOADING = "ORDER_LOADING";
export const ORDER_ERROR = "ORDER_ERROR";
export const ORDER_SUCCESS = "ORDER_SUCCESS";


